### ISSUE TITLE
java.lang.NoClassDefFoundError - .StrTokenizer

### ISSUE THREAD

**Issue by nitinsawant** [ESAPI/esapi-java-legacy#375]
We are upgrading to esapi-2.1.0.1 our DEV and QA environment are working fine with new esapi-2.1.0.1 jar but when we deploy the code in UAT environment we are getting `java.lang.NoClassDefFoundError: org.apache.commons.lang.text.StrTokenizer` error. The DefaultSecurityConfiguration class code
`boolean multivalued = getESAPIProperty("Validator.ConfigurationFile.MultiValued", false);`
is look like not setting default to False.
We are not setting this property in ESAPI.properties file so it should be false.
Any suggestion on how to resolve the issue?

**Comment by xeno6696** [comment]
The best place for ESAPI support questions of this nature is probably Stack Overflow.  My best guess as to your current problem is that you have a dependency in your local environment that isn't present in the UAT environment.  The kind of error you're seeing would mean the ESAPI code isn't even getting executed.  I think commons.io.FileUpload is an undeclared ESAPI dependency I've seen in the past, but not the StrTokenizer.  Trace the class back to a library in your local and make sure it's present on your UAT, either by build or by adding to your web container's classpath.

**Comment by kwwall** [comment]
Also, using JDepend & verbose class loading is useful for diagnosing
problems like this.

-kevin

**Comment by nitinsawant** [comment]
Thanks Matt and Kevin for quick reply. sorry I did not attached the stack trace. it look like executing the ESAPI code but not sure why the property -  boolean multivalued = getESAPIProperty("Validator.ConfigurationFile.MultiValued", false);  is not set to false.

SystemOut     O java.lang.NoClassDefFoundError: org.apache.commons.lang.text.StrTokenizer
 SystemOut     O 	at java.lang.J9VMInternals.verifyImpl(Native Method)
 SystemOut     O 	at java.lang.J9VMInternals.verify(J9VMInternals.java:73)
 SystemOut     O 	at java.lang.J9VMInternals.initialize(J9VMInternals.java:133)
 SystemOut     O 	at java.lang.Class.forNameImpl(Native Method)
 SystemOut     O 	at java.lang.Class.forName(Class.java:238)
 SystemOut     O 	at org.owasp.esapi.util.ObjFactory.make(ObjFactory.java)
 SystemOut     O 	at org.owasp.esapi.ESAPI.securityConfiguration(ESAPI.java)
 SystemOut     O 	at org.owasp.esapi.ESAPI.logFactory(ESAPI.java:137)
 SystemOut     O 	at org.owasp.esapi.ESAPI.getLogger(ESAPI.java:154)
 SystemOut     O 	at org.owasp.esapi.reference.DefaultEncoder.<init>(DefaultEncoder.java:75)
 SystemOut     O 	at org.owasp.esapi.reference.DefaultEncoder.getInstance(DefaultEncoder.java)
 SystemOut     O 	at com.ibm._jsp._editPersonalInfo._jspService(_editPersonalInfo.java:162)

**Comment by xeno6696** [comment]
That looks like you haven't set up your logging framework to use ESAPI's implementation.  Look [here](http://stackoverflow.com/a/34572533/557153) first.
